import { create } from "zustand";

type Language = "en" | "hi" | "ta" | "te";

type Translations = Record<string, Record<string, string>>;

const translations: Translations = {
    en: {
        "profile_title": "Profile & Settings",
        "profile_subtitle": "Manage your account and preferences",
        "account": "Account",
        "liked_songs": "Liked Songs",
        "playlists": "Playlists",
        "home": "Home",
        "search": "Search",
        "pro": "Pro",
        "downloads": "Downloads",
        "profile": "Profile",
        "your_library": "Your Library",
        "admin_dashboard": "Admin Dashboard",
        "plan": "Plan",
        "subscription": "Subscription",
        "pro_plan": "Pro Plan",
        "free_plan": "Free Plan",
        "admin_lifetime": "Lifetime admin access — no expiry",
        "expires": "Expires",
        "time_remaining": "Time Remaining",
        "upgrade_to_pro": "Upgrade to Pro",
        "free_plan_desc": "You're on the Free plan",
        "preferences": "Preferences",
        "notifications": "Notifications",
        "language": "Language",
        "language_note": "Changes will be applied after restarting the app",
        "sign_out": "Sign Out",
        "password_security": "Password & Security",
        "manage_in_clerk": "Manage in Clerk",
        "edit_name": "Edit Name",
        "add_to_playlist": "Add to Playlist",
        "no_playlists": "No playlists yet",
        "added": "Added",
        "add": "Add",
        "removed_from_playlist": "Removed from playlist",
        "added_to_playlist": "Added to playlist",
        "pro_required": "Pro subscription required",
        "login_required": "Please login first",
        "search_placeholder": "Search songs, artists, or genres...",
        "search_title": "Search",
        "search_subtitle": "Find your next favorite track",
        "no_results": "No results found",
        "try_different": "Try a different search term",
        "browse_genres": "Browse Genres",
        "home_greeting_morning": "Good Morning",
        "home_greeting_afternoon": "Good Afternoon",
        "home_greeting_evening": "Good Evening",
        "home_welcome": "Welcome back",
        "recently_listened": "Recently Listened",
        "all_songs": "All Songs",
        "new_releases": "New Releases",
        "no_recent": "No recently listened songs. Start playing!",
        "library_empty": "Library is currently empty.",
        "create_playlist": "Create Playlist",
        "edit_playlist": "Edit Playlist",
        "delete_playlist": "Delete Playlist?",
        "delete_confirm": "This action cannot be undone",
        "playlist_name": "Name",
        "playlist_desc": "Description",
        "cancel": "Cancel",
        "save": "Save",
        "delete": "Delete",
        "back_to_playlists": "Back to Playlists",
        "play_all": "Play All",
        "no_songs_yet": "No songs yet",
        "add_songs_from_library": "Add songs from your library",
        "browse_songs": "Browse Songs",
        "playlists_title": "Playlists",
        "playlists_subtitle": "Your personal collections",
        "no_playlists_yet": "No playlists yet",
        "create_first_playlist": "Create your first playlist to get started",
        "downloads_subtitle": "Your downloaded songs",
        "no_downloads": "No downloads yet",
        "download_songs_here": "Download songs to keep them here",
        "premium_title": "Upgrade to BeatFlow Pro",
        "premium_subtitle": "Skip ads forever and unlock everything",
        "get_pro_now": "Get Pro Now",
        "ad_ends_in": "Ad ends in",
        "advertisement": "ADVERTISEMENT",
        "daily_plan": "Daily",
        "monthly_plan": "Monthly",
        "yearly_plan": "Yearly",
        "per_day": "/day",
        "per_month": "/month",
        "per_year": "/year",
        "popular": "Popular",
        "best_value": "Best Value",
        "ad_free": "Ad-free listening",
        "basic_support": "Basic support",
        "all_daily": "All daily features",
        "high_quality": "High quality audio",
        "priority_support": "Priority support",
        "play_any_order": "Play songs in any order",
        "no_ads": "No ads",
        "all_monthly": "All monthly features",
        "download_songs_feature": "Download songs",
        "exclusive_badges": "Exclusive badges",
        "early_access": "Early access to new features",
        "best_value_desc": "Best value",
        "upgrade_title": "Upgrade to BeatFlow Pro",
        "upgrade_subtitle": "Skip ads forever and unlock everything",
        "get_pro": "Get Pro Now",
        "wallet_title": "Your Wallet",
        "wallet_subtitle": "Manage your wallet balance and transactions",
        "available_balance": "Available Balance",
        "transaction_history": "Transaction History",
        "add_money": "Add Money",
        "set_pin": "Set PIN",
        "enter_pin": "Enter PIN",
        "wallet_pin": "Wallet PIN",
        "confirm": "Confirm",
        "processing": "Processing...",
        "payment_success": "Payment Successful!",
        "payment_failed": "Payment Failed",
        "insufficient_balance": "Insufficient wallet balance",
        "new_albums": "New Albums",
        "no_transactions": "No transactions yet",
        "deposit": "Deposit",
        "withdrawal": "Withdrawal",
        "purchase": "Purchase",
        "status": "Status",
        "completed": "Completed",
        "failed": "Failed",
        "pending": "Pending",
        "amount": "Amount",
        "date": "Date",
        "type": "Type",
        "set_wallet_pin": "Set Wallet PIN",
        "set_wallet_pin_desc": "Create a 4-digit PIN to secure your wallet",
        "enter_wallet_pin": "Enter your 4-digit PIN",
        "verify_pin": "Verify PIN",
        "pin_setup": "PIN Setup",
        "pin_verified": "PIN Verified",
        "songs": "Songs",
        "enter_name": "Please enter a name",
        "playlist_not_found": "Playlist not found",
        "playlist_label": "Playlist",
        "pause": "Pause",
        "play": "Play",
        "add_songs": "Add Songs",
        "table_number": "#",
        "table_title": "Title",
        "songs_count": "songs",
        "liked_songs_title": "Liked Songs",
        "no_liked_songs": "No liked songs yet",
        "start_liking_songs": "Start liking songs to build your collection",
        "album_not_found": "Album not found",
        "go_home": "Go Home",
        "pro_album": "Pro Album",
        "pro_album_desc": "Only Pro users can access this album",
        "explore_pro": "Explore Pro Plans",
        "album_label": "Album",
        "no_songs_album": "No songs in this album",
        "maybe_later": "Maybe Later",
        "exclusive_albums": "Exclusive Pro Albums",
        "download_songs": "Download Songs",
        "ad_free_exp": "Ad-Free Experience",
        "max_balance": "Maximum balance reached!",
        "admin_wallet_info": "Collecting all subscription payments",
        "clear_transactions_title": "Clear all transactions",
        "set_pin_required": "Set PIN - Required",
        "create_pin_desc": "Create 4-digit PIN to use wallet",
        "secure_wallet_desc": "Create a 4-digit PIN to secure your wallet transactions",
        "set_pin_btn": "Set PIN",
        "add_money_wallet": "Add Money to Wallet",
        "secure_transaction": "Secure Transaction",
        "select_amount": "Select amount",
        "custom_amount": "Or enter custom amount",
        "continue": "Continue",
        "enter_pin_title": "Enter PIN",
        "verify_transaction": "Verify your transaction",
        "pin_confirm_desc": "Enter your 4-digit PIN to confirm",
        "confirm_payment": "Confirm Payment",
        "processing_payment": "Processing Payment",
        "adding_wallet": "Adding to wallet...",
        "payment_successful": "Payment Successful!",
        "added_wallet": "added to your wallet",
        "done": "Done",
        "clear_transactions_q": "Clear Transactions?",
        "clear_transactions_desc": "This will remove all transaction history. This action cannot be undone.",
        "clear_all": "Clear All",
        "pin_4_digits": "PIN must be 4 digits",
        "valid_amount": "Please enter a valid amount",
        "enter_4_pin": "Please enter 4-digit PIN",
        "setup_pin_first": "Please set up your PIN first",
        "incorrect_pin": "Incorrect PIN",
        "max_wallet_reached": "Maximum wallet balance reached!",
        "login_subscribe": "Please login to subscribe",
        "insufficient_wallet": "Insufficient wallet balance. Please add money first.",
        "sdk_not_loaded": "Payment SDK not loaded. Please refresh.",
        "payment_failed_retry": "Payment failed. Please try again.",
        "verifying_pin": "Verifying PIN...",
        "processing_payment_wallet": "Processing payment from wallet...",
        "payment_success_pro": "Payment successful! You're now a Pro member.",
        "insufficient_detailed": "Insufficient balance. Please add money to wallet or select a cheaper plan.",
        "beatflow_pro": "BeatFlow Pro",
        "wallet_label": "Wallet",
        "balance_label": "Balance",
        "card_label": "Card",
        "test_mode": "Test Mode",
        "insufficient_bal": "Insufficient balance.",
        "add_money_link": "Add money",
        "pay_from_wallet": "Pay from Wallet",
        "secure_payment": "Secure Payment",
        "encrypted": "Encrypted & Secure",
        "test_card": "Test Card",
        "test_badge": "TEST",
        "encryption_note": "Your payment is secured with 256-bit encryption",
        "enter_password": "Enter Password",
        "verify_payment": "Verify your payment",
        "enter_4_pin_test": "Enter your 4-digit test PIN",
        "processing_payment_title": "Processing Payment",
        "subscription_activated": "Your subscription has been activated",
        "continue_beatflow": "Continue to BeatFlow",
        "payment_failed_title": "Payment Failed",
        "payment_failed_desc": "Something went wrong. Please try again.",
        "try_again": "Try Again",
        "name_updated": "Name updated successfully",
        "failed_update_name": "Failed to update name",
        "select_image": "Please select an image file",
        "image_8mb": "Image must be less than 8MB",
        "profile_pic_updated": "Profile picture updated!",
        "failed_update_pic": "Failed to update profile picture",
        "enter_both_pass": "Please enter both current and new password",
        "pass_8_chars": "Password must be at least 8 characters",
        "pass_uppercase": "Password must contain at least one uppercase letter",
        "pass_lowercase": "Password must contain at least one lowercase letter",
        "pass_number": "Password must contain at least one number",
        "pass_special": "Password must contain at least one special character",
        "pass_request_sent": "Password change request sent to admin for approval!",
        "failed_pass_request": "Failed to submit password change request",
        "failed_save_pref": "Failed to save preferences",
        "view_pic": "View Pic",
        "upload_pic": "Upload Pic",
        "admin_badge": "Admin",
        "security": "Security",
        "change_pass_request": "Change Password Request",
        "request_history": "Request History",
        "approved": "Approved",
        "rejected": "Rejected",
        "approved_label": "Approved",
        "request_pass_title": "Request Password Change",
        "request_pass_desc": "Your request will be sent to admin for approval.",
        "current_pass_label": "Current Password",
        "current_pass_placeholder": "Enter current password",
        "new_pass_label": "New Password",
        "new_pass_placeholder": "Enter new password (min 8 chars)",
        "pass_req_8": "At least 8 characters",
        "pass_req_upper": "One uppercase letter",
        "pass_req_lower": "One lowercase letter",
        "pass_req_num": "One number",
        "pass_req_special": "One special character",
        "sending": "Sending...",
        "send_request": "Send Request",
        "crop_profile": "Crop Profile Picture",
        "zoom": "Zoom",
        "apply": "Apply",
        "pro_sub_required": "Pro subscription required for this album",
        "login_like_songs": "Please login to like songs",
        "pro_album_exclusive": "Exclusive Pro Albums",
        "pro_album_desc_modal": "This album is available exclusively for Pro subscribers. Upgrade your plan to unlock this and many more premium features.",
        "expired": "Expired",
        "user_fallback": "User",
        "pro_badge": "Pro",
        "free_badge": "Free",
        "daily_plan_name": "Daily",
        "monthly_plan_name": "Monthly",
        "yearly_plan_name": "Yearly",
        "admin_plan_name": "Admin (Lifetime)",
        "free_admin": "Free (Admin)",
    },
    hi: {
        "profile_title": "प्रोफ़ाइल और सेटिंग्स",
        "profile_subtitle": "अपने खाते और प्राथमिकताओं को प्रबंधित करें",
        "account": "खाता",
        "liked_songs": "पसंदीदे गाने",
        "playlists": "प्लेलिस्ट",
        "home": "होम",
        "search": "खोजें",
        "pro": "प्रो",
        "downloads": "डाउनलोड",
        "profile": "प्रोफ़ाइल",
        "your_library": "आपकी लाइब्रेरी",
        "admin_dashboard": "एडमिन डैशबोर्ड",
        "plan": "योजना",
        "subscription": "सदस्यता",
        "pro_plan": "प्रो योजना",
        "free_plan": "मुफ्त योजना",
        "admin_lifetime": "आजीवन एडमिन एक्सेस — कोई समाप्ति नहीं",
        "expires": "समाप्त होता है",
        "time_remaining": "शेष समय",
        "upgrade_to_pro": "प्रो में अपग्रेड करें",
        "free_plan_desc": "आप मुफ्त योजना पर हैं",
        "preferences": "प्राथमिकताएं",
        "notifications": "सूचनाएं",
        "language": "भाषा",
        "language_note": "ऐप पुनरारंभ करने के बाद परिवर्तन लागू होंगे",
        "sign_out": "साइन आउट",
        "password_security": "पासवर्ड और सुरक्षा",
        "manage_in_clerk": "Clerk में प्रबंधित करें",
        "edit_name": "नाम संपादित करें",
        "add_to_playlist": "प्लेलिस्ट में जोड़ें",
        "no_playlists": "अभी कोई प्लेलिस्ट नहीं",
        "added": "जोड़ा गया",
        "add": "जोड़ें",
        "removed_from_playlist": "प्लेलिस्ट से हटाया गया",
        "added_to_playlist": "प्लेलिस्ट में जोड़ा गया",
        "pro_required": "प्रो सदस्यता आवश्यक",
        "login_required": "कृपया पहले लॉगिन करें",
        "search_placeholder": "गाने, कलाकार, या शैलियाँ खोजें...",
        "search_title": "खोजें",
        "search_subtitle": "अपना अगला पसंदीदा ट्रैक खोजें",
        "no_results": "कोई परिणाम नहीं मिला",
        "try_different": "कोई अन्य खोज शब्द आज़माएं",
        "browse_genres": "शैलियाँ ब्राउज़ करें",
        "home_greeting_morning": "सुप्रभात",
        "home_greeting_afternoon": "नमस्ते",
        "home_greeting_evening": "शुभ संध्या",
        "home_welcome": "वापसी पर स्वागत",
        "recently_listened": "हाल ही में सुने गए",
        "all_songs": "सभी गाने",
        "new_releases": "नई रिलीज़",
        "no_recent": "कोई हालिया गाने नहीं। चलाना शुरू करें!",
        "library_empty": "लाइब्रेरी वर्तमान में खाली है।",
        "create_playlist": "प्लेलिस्ट बनाएं",
        "edit_playlist": "प्लेलिस्ट संपादित करें",
        "delete_playlist": "प्लेलिस्ट हटाएं?",
        "delete_confirm": "यह क्रिया पूर्ववत नहीं की जा सकती",
        "playlist_name": "नाम",
        "playlist_desc": "विवरण",
        "cancel": "रद्द करें",
        "save": "सहेजें",
        "delete": "हटाएं",
        "back_to_playlists": "प्लेलिस्ट पर वापस जाएं",
        "play_all": "सभी चलाएं",
        "no_songs_yet": "अभी कोई गाने नहीं",
        "add_songs_from_library": "अपनी लाइब्रेरी से गाने जोड़ें",
        "browse_songs": "गाने ब्राउज़ करें",
        "playlists_title": "प्लेलिस्ट",
        "playlists_subtitle": "आपके व्यक्तिगत संग्रह",
        "no_playlists_yet": "अभी कोई प्लेलिस्ट नहीं",
        "create_first_playlist": "शुरू करने के लिए अपनी पहली प्लेलिस्ट बनाएं",
        "downloads_subtitle": "आपके डाउनलोड किए गए गाने",
        "no_downloads": "अभी कोई डाउनलोड नहीं",
        "download_songs_here": "गाने डाउनलोड करें ताकि वे यहां रहें",
        "premium_title": "BeatFlow प्रो में अपग्रेड करें",
        "premium_subtitle": "विज्ञापनों को हमेशा के लिए छोड़ दें और सब कुछ अनलॉक करें",
        "get_pro_now": "अभी प्रो प्राप्त करें",
        "ad_ends_in": "विज्ञापन समाप्त होता है",
        "advertisement": "विज्ञापन",
        "daily_plan": "दैनिक",
        "monthly_plan": "मासिक",
        "yearly_plan": "वार्षिक",
        "per_day": "/दिन",
        "per_month": "/महीना",
        "per_year": "/साल",
        "popular": "लोकप्रिय",
        "best_value": "सर्वोत्तम मूल्य",
        "ad_free": "विज्ञापन-मुक्त सुनना",
        "basic_support": "बेसिक सहायता",
        "all_daily": "सभी दैनिक सुविधाएँ",
        "high_quality": "उच्च गुणवत्ता ऑडियो",
        "priority_support": "प्राथमिकता सहायता",
        "play_any_order": "किसी भी क्रम में गाने चलाएं",
        "no_ads": "कोई विज्ञापन नहीं",
        "all_monthly": "सभी मासिक सुविधाएँ",
        "download_songs_feature": "गाने डाउनलोड करें",
        "exclusive_badges": "विशेष बैज",
        "early_access": "नई सुविधाओं तक जल्दी पहुंच",
        "best_value_desc": "सर्वोत्तम मूल्य",
        "upgrade_title": "BeatFlow प्रो में अपग्रेड करें",
        "upgrade_subtitle": "विज्ञापनों को हमेशा के लिए छोड़ दें और सब कुछ अनलॉक करें",
        "get_pro": "अभी प्रो प्राप्त करें",
        "wallet_title": "आपका वॉलेट",
        "wallet_subtitle": "अपने वॉलेट बैलेंस और लेनदेन को प्रबंधित करें",
        "available_balance": "उपलब्ध शेष राशि",
        "transaction_history": "लेनदेन इतिहास",
        "add_money": "पैसे जोड़ें",
        "set_pin": "पिन सेट करें",
        "enter_pin": "पिन दर्ज करें",
        "wallet_pin": "वॉलेट पिन",
        "confirm": "पुष्टि करें",
        "processing": "प्रसंस्करण...",
        "payment_success": "भुगतान सफल!",
        "payment_failed": "भुगतान विफल",
        "insufficient_balance": "अपर्याप्त वॉलेट शेष",
        "new_albums": "नए एल्बम",
        "no_transactions": "अभी कोई लेनदेन नहीं",
        "deposit": "जमा",
        "withdrawal": "निकासी",
        "purchase": "खरीद",
        "status": "स्थिति",
        "completed": "पूर्ण",
        "failed": "विफल",
        "pending": "प्रगति में",
        "amount": "राशि",
        "date": "तारीख",
        "type": "प्रकार",
        "set_wallet_pin": "वॉलेट पिन सेट करें",
        "set_wallet_pin_desc": "अपने वॉलेट को सुरक्षित करने के लिए 4-अंकीय पिन बनाएं",
        "enter_wallet_pin": "अपना 4-अंकीय पिन दर्ज करें",
        "verify_pin": "पिन सत्यापित करें",
        "pin_setup": "पिन सेटअप",
        "pin_verified": "पिन सत्यापित",
        "songs": "गाने",
        "enter_name": "कृपया एक नाम दर्ज करें",
        "playlist_not_found": "प्लेलिस्ट नहीं मिली",
        "playlist_label": "प्लेलिस्ट",
        "pause": "विराम",
        "play": "चलाएं",
        "add_songs": "गाने जोड़ें",
        "table_number": "#",
        "table_title": "शीर्षक",
        "songs_count": "गाने",
        "liked_songs_title": "पसंदीदा गाने",
        "no_liked_songs": "अभी कोई पसंदीदा गाने नहीं",
        "start_liking_songs": "अपना संग्रह बनाने के लिए गाने पसंद करना शुरू करें",
        "album_not_found": "एल्बम नहीं मिला",
        "go_home": "होम जाएं",
        "pro_album": "प्रो एल्बम",
        "pro_album_desc": "केवल प्रो उपयोगकर्ता इस एल्बम तक पहुंच सकते हैं",
        "explore_pro": "प्रो योजनाएं देखें",
        "album_label": "एल्बम",
        "no_songs_album": "इस एल्बम में कोई गाने नहीं",
        "maybe_later": "शायद बाद में",
        "exclusive_albums": "विशेष प्रो एल्बम",
        "download_songs": "गाने डाउनलोड करें",
        "ad_free_exp": "विज्ञापन-मुक्त अनुभव",
        "max_balance": "अधिकतम शेष राशि!",
        "admin_wallet_info": "सभी उपयोगकर्ताओं से सदस्यता भुगतान एकत्र करना",
        "clear_transactions_title": "सभी लेनदेन मिटाएं",
        "set_pin_required": "पिन सेट करें - आवश्यक",
        "create_pin_desc": "वॉलेट उपयोग के लिए 4-अंकीय पिन बनाएं",
        "secure_wallet_desc": "अपने वॉलेट लेनदेन को सुरक्षित करने के लिए 4-अंकीय पिन बनाएं",
        "set_pin_btn": "पिन सेट करें",
        "add_money_wallet": "वॉलेट में पैसे जोड़ें",
        "secure_transaction": "सुरक्षित लेनदेन",
        "select_amount": "राशि चुनें",
        "custom_amount": "या कस्टम राशि दर्ज करें",
        "continue": "जारी रखें",
        "enter_pin_title": "पिन दर्ज करें",
        "verify_transaction": "अपने लेनदेन की पुष्टि करें",
        "pin_confirm_desc": "पुष्टि करने के लिए अपना 4-अंकीय पिन दर्ज करें",
        "confirm_payment": "भुगतान की पुष्टि करें",
        "processing_payment": "भुगतान प्रसंस्करण",
        "adding_wallet": "वॉलेट में जोड़ा जा रहा है...",
        "payment_successful": "भुगतान सफल!",
        "added_wallet": "वॉलेट में जोड़ा गया",
        "done": "हो गया",
        "clear_transactions_q": "लेनदेन मिटाएं?",
        "clear_transactions_desc": "यह सभी लेनदेन इतिहास को हटा देगा। यह क्रिया पूर्ववत नहीं की जा सकती।",
        "clear_all": "सभी मिटाएं",
        "pin_4_digits": "पिन 4 अंकों का होना चाहिए",
        "valid_amount": "कृपया एक वैध राशि दर्ज करें",
        "enter_4_pin": "कृपया 4-अंकीय पिन दर्ज करें",
        "setup_pin_first": "कृपया पहले अपना पिन सेट करें",
        "incorrect_pin": "गलत पिन",
        "max_wallet_reached": "अधिकतम वॉलेट शेष राशि!",
        "login_subscribe": "कृपया सदस्यता लेने के लिए लॉगिन करें",
        "insufficient_wallet": "अपर्याप्त वॉलेट शेष। कृपया पहले पैसे जोड़ें।",
        "sdk_not_loaded": "भुगतान SDK लोड नहीं हुआ। कृपया रिफ्रेश करें।",
        "payment_failed_retry": "भुगतान विफल। कृपया पुनः प्रयास करें।",
        "verifying_pin": "पिन सत्यापित हो रहा है...",
        "processing_payment_wallet": "वॉलेट से भुगतान प्रसंस्करण...",
        "payment_success_pro": "भुगतान सफल! आप अब प्रो सदस्य हैं।",
        "insufficient_detailed": "अपर्याप्त शेष। कृपया वॉलेट में पैसे जोड़ें या सस्ता प्लान चुनें।",
        "beatflow_pro": "BeatFlow प्रो",
        "wallet_label": "वॉलेट",
        "balance_label": "शेष",
        "card_label": "कार्ड",
        "test_mode": "टेस्ट मोड",
        "insufficient_bal": "अपर्याप्त शेष।",
        "add_money_link": "पैसे जोड़ें",
        "pay_from_wallet": "वॉलेट से भुगतान करें",
        "secure_payment": "सुरक्षित भुगतान",
        "encrypted": "एन्क्रिप्टेड और सुरक्षित",
        "test_card": "टेस्ट कार्ड",
        "test_badge": "टेस्ट",
        "encryption_note": "आपका भुगतान 256-बिट एन्क्रिप्शन से सुरक्षित है",
        "enter_password": "पासवर्ड दर्ज करें",
        "verify_payment": "अपने भुगतान की पुष्टि करें",
        "enter_4_pin_test": "अपना 4-अंकीय टेस्ट पिन दर्ज करें",
        "processing_payment_title": "भुगतान प्रसंस्करण",
        "subscription_activated": "आपकी सदस्यता सक्रिय कर दी गई है",
        "continue_beatflow": "BeatFlow पर जारी रखें",
        "payment_failed_title": "भुगतान विफल",
        "payment_failed_desc": "कुछ गलत हो गया। कृपया पुनः प्रयास करें।",
        "try_again": "पुनः प्रयास करें",
        "name_updated": "नाम सफलतापूर्वक अपडेट किया गया",
        "failed_update_name": "नाम अपडेट करने में विफल",
        "select_image": "कृपया एक छवि फ़ाइल चुनें",
        "image_8mb": "छवि 8MB से कम होनी चाहिए",
        "profile_pic_updated": "प्रोफ़ाइल चित्र अपडेट किया गया!",
        "failed_update_pic": "प्रोफ़ाइल चित्र अपडेट करने में विफल",
        "enter_both_pass": "कृपया वर्तमान और नया पासवर्ड दोनों दर्ज करें",
        "pass_8_chars": "पासवर्ड कम से कम 8 अक्षरों का होना चाहिए",
        "pass_uppercase": "पासवर्ड में कम से कम एक अपरकेस अक्षर होना चाहिए",
        "pass_lowercase": "पासवर्ड में कम से कम एक लोअरकेस अक्षर होना चाहिए",
        "pass_number": "पासवर्ड में कम से कम एक संख्या होनी चाहिए",
        "pass_special": "पासवर्ड में कम से कम एक विशेष वर्ण होना चाहिए",
        "pass_request_sent": "पासवर्ड परिवर्तन अनुरोध प्रशासक के अनुमोदन के लिए भेजा गया!",
        "failed_pass_request": "पासवर्ड परिवर्तन अनुरोध जमा करने में विफल",
        "failed_save_pref": "प्राथमिकताएं सहेजने में विफल",
        "view_pic": "चित्र देखें",
        "upload_pic": "चित्र अपलोड करें",
        "admin_badge": "एडमिन",
        "security": "सुरक्षा",
        "change_pass_request": "पासवर्ड परिवर्तन अनुरोध",
        "request_history": "अनुरोध इतिहास",
        "approved": "अनुमोदित",
        "rejected": "अस्वीकृत",
        "approved_label": "अनुमोदित",
        "request_pass_title": "पासवर्ड परिवर्तन अनुरोध",
        "request_pass_desc": "आपका अनुरोध प्रशासक के अनुमोदन के लिए भेजा जाएगा।",
        "current_pass_label": "वर्तमान पासवर्ड",
        "current_pass_placeholder": "वर्तमान पासवर्ड दर्ज करें",
        "new_pass_label": "नया पासवर्ड",
        "new_pass_placeholder": "नया पासवर्ड दर्ज करें (न्यूनतम 8 अक्षर)",
        "pass_req_8": "कम से कम 8 अक्षर",
        "pass_req_upper": "एक अपरकेस अक्षर",
        "pass_req_lower": "एक लोअरकेस अक्षर",
        "pass_req_num": "एक संख्या",
        "pass_req_special": "एक विशेष वर्ण",
        "sending": "भेजा जा रहा है...",
        "send_request": "अनुरोध भेजें",
        "crop_profile": "प्रोफ़ाइल चित्र क्रॉप करें",
        "zoom": "ज़ूम",
        "apply": "लागू करें",
        "pro_sub_required": "इस एल्बम के लिए प्रो सदस्यता आवश्यक",
        "login_like_songs": "गाने पसंद करने के लिए कृपया लॉगिन करें",
        "pro_album_exclusive": "विशेष प्रो एल्बम",
        "pro_album_desc_modal": "यह एल्बम विशेष रूप से प्रो सदस्यों के लिए उपलब्ध है। इसे और कई प्रीमियम सुविधाओं को अनलॉक करने के लिए अपनी योजना अपग्रेड करें।",
        "expired": "समाप्त",
        "user_fallback": "उपयोगकर्ता",
        "pro_badge": "प्रो",
        "free_badge": "मुफ्त",
        "daily_plan_name": "दैनिक",
        "monthly_plan_name": "मासिक",
        "yearly_plan_name": "वार्षिक",
        "admin_plan_name": "एडमिन (आजीवन)",
        "free_admin": "मुफ्त (एडमिन)",
    },
    ta: {
        "profile_title": "சுயவிவரம் மற்றும் அமைப்புகள்",
        "profile_subtitle": "உங்கள் கணக்கு மற்றும் விருப்பங்களை நிர்வகிக்கவும்",
        "account": "கணக்கு",
        "liked_songs": "விருப்பமான பாடல்கள்",
        "playlists": "இசைப்பட்டியல்கள்",
        "home": "முகப்பு",
        "search": "தேடு",
        "pro": "ப்ரோ",
        "downloads": "பதிவிறக்கங்கள்",
        "profile": "சுயவிவரம்",
        "your_library": "உங்கள் நூலகம்",
        "admin_dashboard": "நிர்வாகி டாஷ்போர்டு",
        "plan": "திட்டம்",
        "subscription": "சந்தா",
        "pro_plan": "ப்ரோ திட்டம்",
        "free_plan": "இலவச திட்டம்",
        "admin_lifetime": "ஆயுள் நிர்வாகி அணுகல் — காலாவதி இல்லை",
        "expires": "காலாவதி",
        "time_remaining": "மீதமுள்ள நேரம்",
        "upgrade_to_pro": "ப்ரோக்கு மேம்படுத்தவும்",
        "free_plan_desc": "நீங்கள் இலவச திட்டத்தில் உள்ளீர்கள்",
        "preferences": "விருப்பங்கள்",
        "notifications": "அறிவிப்புகள்",
        "language": "மொழி",
        "language_note": "பயன்பாட்டை மறுதொடக்கம் செய்த பிறகு மாற்றங்கள் பயன்படுத்தப்படும்",
        "sign_out": "வெளியேறு",
        "password_security": "கடவுச்சொல் மற்றும் பாதுகாப்பு",
        "manage_in_clerk": "Clerk இல் நிர்வகி",
        "edit_name": "பெயரைத் திருத்து",
        "add_to_playlist": "இசைப்பட்டியலில் சேர்",
        "no_playlists": "இன்னும் இசைப்பட்டியல்கள் இல்லை",
        "added": "சேர்க்கப்பட்டது",
        "add": "சேர்",
        "removed_from_playlist": "இசைப்பட்டியலிலிருந்து அகற்றப்பட்டது",
        "added_to_playlist": "இசைப்பட்டியலில் சேர்க்கப்பட்டது",
        "pro_required": "ப்ரோ சந்தா தேவை",
        "login_required": "முதலில் உள்நுழையவும்",
        "search_placeholder": "பாடல்கள், கலைஞர்கள் அல்லது வகைகளைத் தேடுங்கள்...",
        "search_title": "தேடு",
        "search_subtitle": "உங்கள் அடுத்த விருப்பமான டிராக்கைக் கண்டறியுங்கள்",
        "no_results": "முடிவுகள் எதுவும் இல்லை",
        "try_different": "வேறு தேடல் சொல்லை முயற்சிக்கவும்",
        "browse_genres": "விருப்பமான பாடல்கள் தேடு",
        "home_greeting_morning": "காலை வணக்கம்",
        "home_greeting_afternoon": "மதிய வணக்கம்",
        "home_greeting_evening": "மாலை வணக்கம்",
        "home_welcome": "மீண்டும் வரவேற்கிறோம்",
        "recently_listened": "சமீபத்தில் கேட்டது",
        "all_songs": "அனைத்து பாடல்கள்",
        "new_releases": "புதிய வெளியீடுகள்",
        "no_recent": "சமீபத்திய பாடல்கள் இல்லை. இயக்க தொடங்குங்கள்!",
        "library_empty": "நூலகம் தற்போது காலியாக உள்ளது.",
        "create_playlist": "இசைப்பட்டியலை உருவாக்கு",
        "edit_playlist": "இசைப்பட்டியலை திருத்து",
        "delete_playlist": "இசைப்பட்டியலை நீக்கவா?",
        "delete_confirm": "இந்த செயலை ரத்து செய்ய முடியாது",
        "playlist_name": "பெயர்",
        "playlist_desc": "விளக்கம்",
        "cancel": "ரத்து செய்",
        "save": "சேமி",
        "delete": "நீக்கு",
        "back_to_playlists": "இசைப்பட்டியல்களுக்கு திரும்பு",
        "play_all": "அனைத்தையும் இயக்கு",
        "no_songs_yet": "இன்னும் பாடல்கள் இல்லை",
        "add_songs_from_library": "உங்கள் நூலகத்திலிருந்து பாடல்களைச் சேர்க்கவும்",
        "browse_songs": "தேடு",
        "playlists_title": "இசைப்பட்டியல்கள்",
        "playlists_subtitle": "உங்கள் தனிப்பட்ட சேகரிப்புகள்",
        "no_playlists_yet": "இன்னும் இசைப்பட்டியல்கள் இல்லை",
        "create_first_playlist": "தொடங்க உங்கள் முதல் இசைப்பட்டியலை உருவாக்குங்கள்",
        "downloads_subtitle": "உங்கள் பதிவிறக்கிய பாடல்கள்",
        "no_downloads": "இன்னும் பதிவிறக்கங்கள் இல்லை",
        "download_songs_here": "பாடல்களைப் பதிவிறக்கம் செய்யுங்கள்",
        "premium_title": "BeatFlow ப்ரோக்கு மேம்படுத்தவும்",
        "premium_subtitle": "விளம்பரங்களை என்றென்றும் தவிர்க்கவும்",
        "get_pro_now": "இப்போது ப்ரோ பெறுங்கள்",
        "ad_ends_in": "விளம்பரம் முடிகிறது",
        "advertisement": "விளம்பரம்",
        "daily_plan": "தினசரி",
        "monthly_plan": "மாதாந்திர",
        "yearly_plan": "ஆண்டு",
        "per_day": "/நாள்",
        "per_month": "/மாதம்",
        "per_year": "/ஆண்டு",
        "popular": "பிரபலமானது",
        "best_value": "சிறந்த மதிப்பு",
        "ad_free": "விளம்பரமில்லாத கேட்பு",
        "basic_support": "அடிப்படை ஆதரவு",
        "all_daily": "அனைத்து தினசரி அம்சங்கள்",
        "high_quality": "உயர் தர ஆடியோ",
        "priority_support": "முன்னுரிமை ஆதரவு",
        "play_any_order": "எந்த வரிசையிலும் பாடல்களை இயக்கு",
        "no_ads": "விளம்பரங்கள் இல்லை",
        "all_monthly": "அனைத்து மாதாந்திர அம்சங்கள்",
        "download_songs_feature": "பாடல்களைப் பதிவிறக்கு",
        "exclusive_badges": "பிரத்யேக பேட்ஜ்கள்",
        "early_access": "புதிய அம்சங்களுக்கு முன்கூட்டியே அணுகல்",
        "best_value_desc": "சிறந்த மதிப்பு",
        "upgrade_title": "BeatFlow ப்ரோக்கு மேம்படுத்தவும்",
        "upgrade_subtitle": "விளம்பரங்களை என்றென்றும் தவிர்க்கவும்",
        "get_pro": "இப்போது ப்ரோ பெறுங்கள்",
        "wallet_title": "உங்கள் வாலெட்",
        "wallet_subtitle": "உங்கள் வாலெட் இருப்பு மற்றும் பரிவர்த்தனைகளை நிர்வகிக்கவும்",
        "available_balance": "கிடைக்கும் இருப்பு",
        "transaction_history": "பரிவர்த்தனை வரலாறு",
        "add_money": "பணம் சேர்",
        "set_pin": "பின் அமை",
        "enter_pin": "பின் உள்ளிடு",
        "wallet_pin": "வாலெட் பின்",
        "confirm": "உறுதிப்படுத்து",
        "processing": "செயலாக்கம்...",
        "payment_success": "கட்டணம் வெற்றி!",
        "payment_failed": "கட்டணம் தோல்வி",
        "insufficient_balance": "போதுமான வாலெட் இருப்பு இல்லை",
        "new_albums": "புதிய ஆல்பங்கள்",
        "no_transactions": "இன்னும் பரிவர்த்தனைகள் இல்லை",
        "deposit": "வைப்பு",
        "withdrawal": "வாபஸ்",
        "purchase": "வாங்குதல்",
        "status": "நிலை",
        "completed": "முடிந்தது",
        "failed": "தோல்வி",
        "pending": "நிலுவையில்",
        "amount": "தொகை",
        "date": "தேதி",
        "type": "வகை",
        "set_wallet_pin": "வாலெட் பின் அமை",
        "set_wallet_pin_desc": "உங்கள் வாலெட்டை பாதுகாக்க 4 இலக்க பின் உருவாக்குங்கள்",
        "enter_wallet_pin": "உங்கள் 4 இலக்க பின் உள்ளிடுங்கள்",
        "verify_pin": "பின் சரிபார்",
        "pin_setup": "பின் அமைப்பு",
        "pin_verified": "பின் சரிபார்க்கப்பட்டது",
        "songs": "பாடல்கள்",
        "enter_name": "தயவுசெய்து பெயரை உள்ளிடுங்கள்",
        "playlist_not_found": "இசைப்பட்டி கிடைக்கவில்லை",
        "playlist_label": "இசைப்பட்டி",
        "pause": "இடைநிறுத்து",
        "play": "இயக்கு",
        "add_songs": "பாடல்களை சேர்",
        "table_number": "#",
        "table_title": "தலைப்பு",
        "songs_count": "பாடல்கள்",
        "liked_songs_title": "விருப்பமான பாடல்கள்",
        "no_liked_songs": "இன்னும் விருப்பமான பாடல்கள் இல்லை",
        "start_liking_songs": "உங்கள் சேகரிப்பை உருவாக்க பாடல்களை விரும்ப தொடங்குங்கள்",
        "album_not_found": "ஆல்பம் கிடைக்கவில்லை",
        "go_home": "முகப்புக்கு செல்",
        "pro_album": "ப்ரோ ஆல்பம்",
        "pro_album_desc": "ப்ரோ பயனர்கள் மட்டுமே இந்த ஆல்பத்தை அணுக முடியும்",
        "explore_pro": "ப்ரோ திட்டங்களை ஆராயுங்கள்",
        "album_label": "ஆல்பம்",
        "no_songs_album": "இந்த ஆல்பத்தில் பாடல்கள் இல்லை",
        "maybe_later": "பிறகு பார்க்கலாம்",
        "exclusive_albums": "பிரத்யேக ப்ரோ ஆல்பங்கள்",
        "download_songs": "பாடல்களை பதிவிறக்கு",
        "ad_free_exp": "விளம்பரமில்லா அனுபவம்",
        "max_balance": "அதிகபட்ச இருப்பு!",
        "admin_wallet_info": "அனைத்து பயனர்களிடமிருந்து சந்தா கட்டணங்கள் சேகரிப்பு",
        "clear_transactions_title": "அனைத்து பரிவர்த்தனைகளையும் அழி",
        "set_pin_required": "பின் அமை - அவசியம்",
        "create_pin_desc": "வாலெட் பயன்பாட்டிற்கு 4 இலக்க பின் உருவாக்குங்கள்",
        "secure_wallet_desc": "உங்கள் வாலெட் பரிவர்த்தனைகளை பாதுகாக்க 4 இலக்க பின் உருவாக்குங்கள்",
        "set_pin_btn": "பின் அமை",
        "add_money_wallet": "வாலெட்டில் பணம் சேர்",
        "secure_transaction": "பாதுகாப்பான பரிவர்த்தனை",
        "select_amount": "தொகையை தேர்வு செய்",
        "custom_amount": "அல்லது தனிப்பயன் தொகை உள்ளிடு",
        "continue": "தொடரவும்",
        "enter_pin_title": "பின் உள்ளிடு",
        "verify_transaction": "உங்கள் பரிவர்த்தனையை சரிபார்க்கவும்",
        "pin_confirm_desc": "உறுதிப்படுத்த உங்கள் 4 இலக்க பின் உள்ளிடுங்கள்",
        "confirm_payment": "கட்டணத்தை உறுதிப்படுத்து",
        "processing_payment": "கட்டண செயலாக்கம்",
        "adding_wallet": "வாலெட்டில் சேர்க்கப்படுகிறது...",
        "payment_successful": "கட்டணம் வெற்றி!",
        "added_wallet": "வாலெட்டில் சேர்க்கப்பட்டது",
        "done": "முடிந்தது",
        "clear_transactions_q": "பரிவர்த்தனைகளை அழிக்கவா?",
        "clear_transactions_desc": "இது அனைத்து பரிவர்த்தனை வரலாற்றையும் அகற்றும். இந்த செயலை ரத்து செய்ய முடியாது.",
        "clear_all": "அனைத்தையும் அழி",
        "pin_4_digits": "பின் 4 இலக்கங்களாக இருக்க வேண்டும்",
        "valid_amount": "தயவுசெய்து செல்லுபடியாகும் தொகையை உள்ளிடுங்கள்",
        "enter_4_pin": "தயவுசெய்து 4 இலக்க பின் உள்ளிடுங்கள்",
        "setup_pin_first": "தயவுசெய்து முதலில் உங்கள் பின் அமைக்கவும்",
        "incorrect_pin": "தவறான பின்",
        "max_wallet_reached": "அதிகபட்ச வாலெட் இருப்பு!",
        "login_subscribe": "தயவுசெய்து சந்தா பெற உள்நுழையவும்",
        "insufficient_wallet": "போதுமான வாலெட் இருப்பு இல்லை. தயவுசெய்து முதலில் பணம் சேர்க்கவும்.",
        "sdk_not_loaded": "கட்டண SDK லோடு ஆகவில்லை. தயவுசெய்து ரிஃப்ரெஷ் செய்யவும்.",
        "payment_failed_retry": "கட்டணம் தோல்வி. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.",
        "verifying_pin": "பின் சரிபார்க்கப்படுகிறது...",
        "processing_payment_wallet": "வாலெட்டிலிருந்து கட்டண செயலாக்கம்...",
        "payment_success_pro": "கட்டணம் வெற்றி! நீங்கள் இப்போது ப்ரோ உறுப்பினர்.",
        "insufficient_detailed": "போதுமான இருப்பு இல்லை. தயவுசெய்து வாலெட்டில் பணம் சேர்க்கவும் அல்லது மலிவான திட்டத்தை தேர்வு செய்யவும்.",
        "beatflow_pro": "BeatFlow ப்ரோ",
        "wallet_label": "வாலெட்",
        "balance_label": "இருப்பு",
        "card_label": "கார்டு",
        "test_mode": "சோதனை முறை",
        "insufficient_bal": "போதுமான இருப்பு இல்லை.",
        "add_money_link": "பணம் சேர்",
        "pay_from_wallet": "வாலெட்டிலிருந்து கட்டணம்",
        "secure_payment": "பாதுகாப்பான கட்டணம்",
        "encrypted": "என்கிரிப்டட் மற்றும் பாதுகாப்பானது",
        "test_card": "சோதனை கார்டு",
        "test_badge": "சோதனை",
        "encryption_note": "உங்கள் கட்டணம் 256-பிட் என்கிரிப்ஷனால் பாதுகாக்கப்படுகிறது",
        "enter_password": "கடவுச்சொல் உள்ளிடு",
        "verify_payment": "உங்கள் கட்டணத்தை சரிபார்க்கவும்",
        "enter_4_pin_test": "உங்கள் 4 இலக்க சோதனை பின் உள்ளிடுங்கள்",
        "processing_payment_title": "கட்டண செயலாக்கம்",
        "subscription_activated": "உங்கள் சந்தா செயல்படுத்தப்பட்டுள்ளது",
        "continue_beatflow": "BeatFlow க்கு தொடரவும்",
        "payment_failed_title": "கட்டணம் தோல்வி",
        "payment_failed_desc": "ஏதோ தவறு. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.",
        "try_again": "மீண்டும் முயற்சிக்கவும்",
        "name_updated": "பெயர் வெற்றிகரமாக புதுப்பிக்கப்பட்டது",
        "failed_update_name": "பெயர் புதுப்பிக்க தவறியது",
        "select_image": "தயவுசெய்து பட கோப்பை தேர்வு செய்யவும்",
        "image_8mb": "படம் 8MB க்கு குறைவாக இருக்க வேண்டும்",
        "profile_pic_updated": "சுயவிவர படம் புதுப்பிக்கப்பட்டது!",
        "failed_update_pic": "சுயவிவர படம் புதுப்பிக்க தவறியது",
        "enter_both_pass": "தயவுசெய்து தற்போதைய மற்றும் புதிய கடவுச்சொல் இரண்டையும் உள்ளிடுங்கள்",
        "pass_8_chars": "கடவுச்சொல் குறைந்தது 8 எழுத்துக்கள் இருக்க வேண்டும்",
        "pass_uppercase": "கடவுச்சொல்லில் குறைந்தது ஒரு பெரிய எழுத்து இருக்க வேண்டும்",
        "pass_lowercase": "கடவுச்சொல்லில் குறைந்தது ஒரு சிறிய எழுத்து இருக்க வேண்டும்",
        "pass_number": "கடவுச்சொல்லில் குறைந்தது ஒரு எண் இருக்க வேண்டும்",
        "pass_special": "கடவுச்சொல்லில் குறைந்தது ஒரு சிறப்பு எழுத்து இருக்க வேண்டும்",
        "pass_request_sent": "கடவுச்சொல் மாற்றம் நிர்வாகி அங்கீகாரத்திற்கு அனுப்பப்பட்டது!",
        "failed_pass_request": "கடவுச்சொல் மாற்ற கோரிக்கை தவறியது",
        "failed_save_pref": "விருப்பங்களை சேமிக்க தவறியது",
        "view_pic": "படம் காண்க",
        "upload_pic": "படம் பதிவேற்று",
        "admin_badge": "நிர்வாகி",
        "security": "பாதுகாப்பு",
        "change_pass_request": "கடவுச்சொல் மாற்ற கோரிக்கை",
        "request_history": "கோரிக்கை வரலாறு",
        "approved": "அங்கீகரிக்கப்பட்டது",
        "rejected": "நிராகரிக்கப்பட்டது",
        "approved_label": "அங்கீகரிக்கப்பட்டது",
        "request_pass_title": "கடவுச்சொல் மாற்ற கோரிக்கை",
        "request_pass_desc": "உங்கள் கோரிக்கை நிர்வாகி அங்கீகாரத்திற்கு அனுப்பப்படும்.",
        "current_pass_label": "தற்போதைய கடவுச்சொல்",
        "current_pass_placeholder": "தற்போதைய கடவுச்சொல் உள்ளிடு",
        "new_pass_label": "புதிய கடவுச்சொல்",
        "new_pass_placeholder": "புதிய கடவுச்சொல் உள்ளிடு (குறைந்தது 8 எழுத்துக்கள்)",
        "pass_req_8": "குறைந்தது 8 எழுத்துக்கள்",
        "pass_req_upper": "ஒரு பெரிய எழுத்து",
        "pass_req_lower": "ஒரு சிறிய எழுத்து",
        "pass_req_num": "ஒரு எண்",
        "pass_req_special": "ஒரு சிறப்பு எழுத்து",
        "sending": "அனுப்பப்படுகிறது...",
        "send_request": "கோரிக்கை அனுப்பு",
        "crop_profile": "சுயவிவர படம் பயிர்",
        "zoom": "ஜூம்",
        "apply": "பயன்படுத்து",
        "pro_sub_required": "இந்த ஆல்பத்திற்கு ப்ரோ சந்தா தேவை",
        "login_like_songs": "பாடல்களை விரும்ப தயவுசெய்து உள்நுழையவும்",
        "pro_album_exclusive": "பிரத்யேக ப்ரோ ஆல்பங்கள்",
        "pro_album_desc_modal": "இந்த ஆல்பம் பிரத்யேகமாக ப்ரோ சந்தாதாரர்களுக்கு கிடைக்கும். இதை மற்றும் பல பிரீமியம் அம்சங்களை திறக்க உங்கள் திட்டத்தை மேம்படுத்தவும்.",
        "expired": "காலாவதி",
        "user_fallback": "பயனர்",
        "pro_badge": "ப்ரோ",
        "free_badge": "இலவசம்",
        "daily_plan_name": "தினசரி",
        "monthly_plan_name": "மாதாந்திர",
        "yearly_plan_name": "ஆண்டு",
        "admin_plan_name": "நிர்வாகி (ஆயுள்)",
        "free_admin": "இலவசம் (நிர்வாகி)",
    },
    te: {
        "profile_title": "ప్రొఫైల్ & సెట్టింగ్‌లు",
        "profile_subtitle": "మీ ఖాతా మరియు ప్రాధాన్యతలను నిర్వహించండి",
        "account": "ఖాతా",
        "liked_songs": "ఇష్టమైన పాటలు",
        "playlists": "ప్లేజాబితాలు",
        "home": "హోమ్",
        "search": "శోధన",
        "pro": "ప్రో",
        "downloads": "డౌన్‌లోడ్‌లు",
        "profile": "ప్రొఫైల్",
        "your_library": "మీ లైబ్రరీ",
        "admin_dashboard": "అడ్మిన్ డాష్‌బోర్డ్",
        "plan": "ప్లాన్",
        "subscription": "సబ్‌స్క్రిప్షన్",
        "pro_plan": "ప్రో ప్లాన్",
        "free_plan": "ఉచిత ప్లాన్",
        "admin_lifetime": "జీవితకాల అడ్మిన్ యాక్సెస్ — గడువు లేదు",
        "expires": "గడువు ముగుస్తుంది",
        "time_remaining": "మిగిలిన సమయం",
        "upgrade_to_pro": "ప్రోకు అప్‌గ్రేడ్ చేయండి",
        "free_plan_desc": "మీరు ఉచిత ప్లాన్‌లో ఉన్నారు",
        "preferences": "ప్రాధాన్యతలు",
        "notifications": "నోటిఫికేషన్‌లు",
        "language": "భాష",
        "language_note": "యాప్‌ను పునఃప్రారంభించిన తర్వాత మార్పులు వర్తిస్తాయి",
        "sign_out": "సైన్ అవుట్",
        "password_security": "పాస్‌వర్డ్ మరియు భద్రత",
        "manage_in_clerk": "Clerkలో నిర్వహించు",
        "edit_name": "పేరు సవరించు",
        "add_to_playlist": "ప్లేజాబితాకు జోడించు",
        "no_playlists": "ఇంకా ప్లేజాబితాలు లేవు",
        "added": "జోడించబడింది",
        "add": "జోడించు",
        "removed_from_playlist": "ప్లేజాబితా నుండి తీసివేయబడింది",
        "added_to_playlist": "ప్లేజాబితాకు జోడించబడింది",
        "pro_required": "ప్రో సబ్‌స్క్రిప్షన్ అవసరం",
        "login_required": "దయచేసి ముందుగా లాగిన్ అవ్వండి",
        "search_placeholder": "పాటలు, కళాకారులు లేదా శైలులను శోధించండి...",
        "search_title": "శోధన",
        "search_subtitle": "మీ తదుపరి ఇష్టమైన ట్రాక్‌ను కనుగొనండి",
        "no_results": "ఫలితాలు లేవు",
        "try_different": "వేరే శోధన పదాన్ని ప్రయత్నించండి",
        "browse_genres": "శైలులను బ్రౌజ్ చేయండి",
        "home_greeting_morning": "శుభోదయం",
        "home_greeting_afternoon": "మధ్యాహ్నం శుభాకాంక్షలు",
        "home_greeting_evening": "సాయంత్రం శుభాకాంక్షలు",
        "home_welcome": "మళ్లీ స్వాగతం",
        "recently_listened": "ఇటీవల విన్నవి",
        "all_songs": "అన్ని పాటలు",
        "new_releases": "కొత్త విడుదలలు",
        "no_recent": "ఇటీవల విన్న పాటలు లేవు. ప్లే చేయడం ప్రారంభించండి!",
        "library_empty": "లైబ్రరీ ప్రస్తుతం ఖాళీగా ఉంది.",
        "create_playlist": "ప్లేజాబితాను సృష్టించు",
        "edit_playlist": "ప్లేజాబితాను సవరించు",
        "delete_playlist": "ప్లేజాబితాను తొలగించాలా?",
        "delete_confirm": "ఈ చర్యను రద్దు చేయలేరు",
        "playlist_name": "పేరు",
        "playlist_desc": "వివరణ",
        "cancel": "రద్దు చేయి",
        "save": "సేవ్",
        "delete": "తొలగించు",
        "back_to_playlists": "ప్లేజాబితాలకు తిరిగి వెళ్ళు",
        "play_all": "అన్నింటినీ ప్లే చేయి",
        "no_songs_yet": "ఇంకా పాటలు లేవు",
        "add_songs_from_library": "మీ లైబ్రరీ నుండి పాటలను జోడించండి",
        "browse_songs": "పాటలను బ్రౌజ్ చేయండి",
        "playlists_title": "ప్లేజాబితాలు",
        "playlists_subtitle": "మీ వ్యక్తిగత సేకరణలు",
        "no_playlists_yet": "ఇంకా ప్లేజాబితాలు లేవు",
        "create_first_playlist": "ప్రారంభించడానికి మీ మొదటి ప్లేజాబితాను సృష్టించండి",
        "downloads_subtitle": "మీ డౌన్‌లోడ్ చేసిన పాటలు",
        "no_downloads": "ఇంకా డౌన్‌లోడ్‌లు లేవు",
        "download_songs_here": "పాటలను డౌన్‌లోడ్ చేయండి",
        "premium_title": "BeatFlow ప్రోకు అప్‌గ్రేడ్ చేయండి",
        "premium_subtitle": "ప్రకటనలను ఎప్పటికీ దాటవేయండి",
        "get_pro_now": "ఇప్పుడు ప్రో పొందండి",
        "ad_ends_in": "ప్రకటన ముగుస్తుంది",
        "advertisement": "ప్రకటన",
        "daily_plan": "రోజువారీ",
        "monthly_plan": "నెలవారీ",
        "yearly_plan": "సంవత్సర",
        "per_day": "/రోజు",
        "per_month": "/నెల",
        "per_year": "/సంవత్సరం",
        "popular": "ప్రసిద్ధ",
        "best_value": "ఉత్తమ విలువ",
        "ad_free": "ప్రకటన-రహిత వినడం",
        "basic_support": "ప్రాథమిక మద్దతు",
        "all_daily": "అన్ని రోజువారీ లక్షణాలు",
        "high_quality": "అధిక నాణ్యత ఆడియో",
        "priority_support": "ప్రాధాన్యత మద్దతు",
        "play_any_order": "ఏ క్రమంలోనైనా పాటలను ప్లే చేయండి",
        "no_ads": "ప్రకటనలు లేవు",
        "all_monthly": "అన్ని నెలవారీ లక్షణాలు",
        "download_songs_feature": "పాటలను డౌన్‌లోడ్ చేయండి",
        "exclusive_badges": "ప్రత్యేక బ్యాడ్జ్‌లు",
        "early_access": "కొత్త లక్షణాలకు ముందస్తు యాక్సెస్",
        "best_value_desc": "ఉత్తమ విలువ",
        "upgrade_title": "BeatFlow ప్రోకు అప్‌గ్రేడ్ చేయండి",
        "upgrade_subtitle": "ప్రకటనలను ఎప్పటికీ దాటవేయండి",
        "get_pro": "ఇప్పుడు ప్రో పొందండి",
        "wallet_title": "మీ వాలెట్",
        "wallet_subtitle": "మీ వాలెట్ బ్యాలెన్స్ మరియు లావాదేవీలను నిర్వహించండి",
        "available_balance": "అందుబాటులో ఉన్న బ్యాలెన్స్",
        "transaction_history": "లావాదేవీ చరిత్ర",
        "add_money": "డబ్బు జోడించు",
        "set_pin": "PIN సెట్ చేయి",
        "enter_pin": "PIN నమోదు చేయి",
        "wallet_pin": "వాలెట్ PIN",
        "confirm": "నిర్ధారించు",
        "processing": "ప్రాసెసింగ్...",
        "payment_success": "చెల్లింపు విజయవంతం!",
        "payment_failed": "చెల్లింపు విఫలమైంది",
        "insufficient_balance": "సరిపోని వాలెట్ బ్యాలెన్స్",
        "new_albums": "కొత్త ఆల్బమ్‌లు",
        "no_transactions": "ఇంకా లావాదేవీలు లేవు",
        "deposit": "డిపాజిట్",
        "withdrawal": "విత్‌డ్రా",
        "purchase": "కొనుగోలు",
        "status": "స్థితి",
        "completed": "పూర్తయింది",
        "failed": "విఫలమైంది",
        "pending": "పెండింగ్‌లో",
        "amount": "మొత్తం",
        "date": "తేదీ",
        "type": "రకం",
        "set_wallet_pin": "వాలెట్ PIN సెట్ చేయి",
        "set_wallet_pin_desc": "మీ వాలెట్‌ను సురక్షితం చేయడానికి 4 అంకెల PIN సృష్టించండి",
        "enter_wallet_pin": "మీ 4 అంకెల PIN నమోదు చేయండి",
        "verify_pin": "PIN సరిచూడు",
        "pin_setup": "PIN సెటప్",
        "pin_verified": "PIN సరిచూడబడింది",
    },
};

interface LanguageStore {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

export const useLanguageStore = create<LanguageStore>((set, get) => ({
    language: (localStorage.getItem("beatflow_language") as Language) || "en",
    setLanguage: (lang) => {
        localStorage.setItem("beatflow_language", lang);
        set({ language: lang });
    },
    t: (key: string) => {
        const { language } = get();
        return translations[language]?.[key] || translations.en[key] || key;
    },
}));
    